//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group10_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PermitRequests = new HashSet<PermitRequest>();
        }
    
        public string paymentID { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        [Display(Name = "Payment Method")]
        public string paymentMethod { get; set; }
        public Nullable<double> last4CardDigit { get; set; }
        public string cardHolderName { get; set; }
        public Nullable<bool> paymentApproved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermitRequest> PermitRequests { get; set; }
    }
}
