//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group10_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RE()
        {
            this.EmailArchives = new HashSet<EmailArchive>();
            this.Permits = new HashSet<Permit>();
            this.PermitRequests = new HashSet<PermitRequest>();
        }
    
        public string ID { get; set; }
        [Display(Name = "Contact Person Name")]
        public string contactPersonName { get; set; }
        public string password { get; set; }
        [Display(Name = "Created Date")]
        public Nullable<System.DateTime> createdDate { get; set; }
        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "Organization Name")]
        public string organizationName { get; set; }
        [Display(Name = "Organization Address")]
        public string organizationAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailArchive> EmailArchives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permit> Permits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermitRequest> PermitRequests { get; set; }
        public virtual RESite RESite { get; set; }
    }
}
