//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group10_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> dateOfDecision { get; set; }
        public string finalDecision { get; set; }
        public string description { get; set; }
        public string EOID { get; set; }
        public string permitRequestID { get; set; }
    
        public virtual EO EO { get; set; }
        public virtual PermitRequest PermitRequest { get; set; }
    }
}
