//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group10_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvironmentalPermit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnvironmentalPermit()
        {
            this.PermitRequests = new HashSet<PermitRequest>();
        }
    
        public string permitID { get; set; }
        public string permitName { get; set; }
        public Nullable<double> permitFee { get; set; }
        public string description { get; set; }
        public string paymentCtrlBy { get; set; }
    
        public virtual OPS_CPP OPS_CPP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermitRequest> PermitRequests { get; set; }
    }
}
