//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group10_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group10_DBEntities : DbContext
    {
        public Group10_DBEntities()
            : base("name=Group10_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Decision> Decisions { get; set; }
        public virtual DbSet<EmailArchive> EmailArchives { get; set; }
        public virtual DbSet<EnvironmentalPermit> EnvironmentalPermits { get; set; }
        public virtual DbSet<EO> EOs { get; set; }
        public virtual DbSet<OPS_CPP> OPS_CPP { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Permit> Permits { get; set; }
        public virtual DbSet<PermitRequest> PermitRequests { get; set; }
        public virtual DbSet<RE> REs { get; set; }
        public virtual DbSet<RequestStatu> RequestStatus { get; set; }
        public virtual DbSet<RESite> RESites { get; set; }
    }
}
