//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group10_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public string permitID { get; set; }
        public Nullable<System.DateTime> dateOfIssue { get; set; }
        public string duration { get; set; }
        public string description { get; set; }
        public string issuedBy { get; set; }
        public string issuedTo { get; set; }
        public string relatedTo { get; set; }
    
        public virtual EO EO { get; set; }
        public virtual RE RE { get; set; }
        public virtual PermitRequest PermitRequest { get; set; }
    }
}
