//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group10_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermitRequest()
        {
            this.Decisions = new HashSet<Decision>();
            this.Permits = new HashSet<Permit>();
            this.RequestStatus = new HashSet<RequestStatus>();
        }
    
        public string requestNo { get; set; }
        public Nullable<System.DateTime> dateOfRequest { get; set; }
        public string activityDescription { get; set; }
        public Nullable<System.DateTime> activityStartDate { get; set; }
        public Nullable<System.DateTime> activityDuration { get; set; }
        public Nullable<double> permitFee { get; set; }
        public string permitTypeID { get; set; }
        public string permitREID { get; set; }
        public string permitPayment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decision> Decisions { get; set; }
        public virtual EnvironmentalPermit EnvironmentalPermit { get; set; }
        public virtual Payment Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permit> Permits { get; set; }
        public virtual RE RE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestStatus> RequestStatus { get; set; }
    }
}
